### ISSUE TITLE
An error occurred in the collision condition

### ISSUE THREAD

**Issue by TejaswiniMedi** [BTHeinbach/gym-flp#12]
I'm attaching the new condition of collision:
if not **(x[i]+0.5*l[i] < x[j]-0.5*l[j] or x[i]-0.5*l[i] > x[j]+0.5*l[j] or y[i]-0.5*w[i] > y[j]+0.5*w[j] or y[i]+0.5*w[i] < y[j]-0.5*w[j])**:
    collision = True

**Comment by BTHeinbach** [comment]
Identical to issue #7
