### ISSUE TITLE
Render facilities images in a similar color and avoid black facility images

### ISSUE THREAD

**Issue by TejaswiniMedi** [BTHeinbach/gym-flp#16]
The following changes are to be made in the ConvertCoordinatesToState(self, state_prelim) method : 
        **R = np.array((p-np.min(p))/(np.max(p)-np.min(p))*0).astype(int)
        R[R == 0] = 20
        G = np.array((sources-np.min(sources))/(np.max(sources)-np.min(sources))*255).astype(int)
        G[G == 0] = 20
        B = np.array((sinks-np.min(sinks))/(np.max(sinks)-np.min(sinks))*0).astype(int)
        B[B == 0] = 20**

**Comment by BTHeinbach** [comment]
in progress
